### ISSUE TITLE
Remove references to Zipkin

### ISSUE THREAD

**Issue by Iteratrix** [smartupio/zipkin-datadog-reporter#6]
This is purely a Datadog reporter with no real relation to the Zipkin application, so I'm not sure why most classes and the project name reference Zipkin so often.

If there's something I'm missing that ties this span reporter to Zipkin, then please let me know. Otherwise, I think yanking those references out might do a lot to prevent confusion.

**Comment by tylerbenson** [comment]
@Diagoras This is specifically a reporter that can be used with zipkin/brave to collect spans, aggregate them into traces, and report them to a Datadog agent.  The project name was chosen on advice from @adriancole and the convention followed in the zipkin community.

**Comment by codefromthecrypt** [comment]
you could name it zipkin-reporter-datadog as the library used is
zipkin-reporter


if only used in brave you could consider refactoring to be a
FinishedSpanHandler and using the localRoot concept to do grouping for you.
this is how we did 100% collection for haystack recently.

**Comment by Iteratrix** [comment]
@tylerbenson @adriancole Got it. I thought that Brave was independent of Zipkin, but if it's related then the naming convention makes sense to me. I'll close this ticket, thanks for the clarification.
